runtime: python37

handlers:
- url: /
  static_files: index.html
  upload: index.html
- url: /css/(.*)
  static_files: css/\1
  upload: css/.*
- url: /js/(.*)
  static_files: js/\1
  upload: js/.*
- url: /(.*)
  static_files: \1.html
  upload: (.*)\.html
